# this file is responsible for:
# Validating incoming requests
# Defining exactly what the API returns
# Preventing accidental data leaks
# Making API backward-compatible

# Design Decisions: we'll define three schema types per entity:
# create schema -> what client sends
# update schema -> what client can modify
# read schems -> what client receives

# validation happens before your code runs

# By using Pydantic’s Field validation, you are ensuring that "bad data" never even reaches your database.
from pydantic import BaseModel, Field
from typing import Optional

# this exists because:
# DRY (don't repeat yourself)
# validation rules in one place
# enforces API Contract
class ItemBase(BaseModel):
    # ... (The Ellipsis): This marks the field as Required. If a user tries to create an item without a name, FastAPI will automatically return a 422 Unprocessable Entity error.
    # min_length=1: Prevents empty strings (""). This is crucial for data integrity—you don't want "ghost" items with no names in your UI.
    # max_length=100: Protects your database. If your database column is defined as VARCHAR(100), this validation prevents a "Data too long" crash by catching the error at the API gate.
    name: str = Field(..., min_length=1, max_length=100)
    # None: This marks the field as Optional. If the user doesn't provide a description, it defaults to null (None) in Python.
    description: Optional[str] = Field(None, max_length=255)

# POST /items
class ItemCreate(ItemBase):
    # same feild as ItemBase
    # semantic clarity (itemCreate != itemIead)
    pass

# PUT /items/{id}
class ItemUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    description: Optional[str] = Field(None, max_length=255)

# Read Schema (Responses)
# This is Inheritance. It means ItemRead automatically gets the name and description fields (and their validation rules) that you defined in ItemBase. You don't have to type them again.
class ItemRead(ItemBase):
    # Since the ID is generated by the database after an item is created, we only include it in the "Read" version, not the "Create" version.
    id: int

    # This is a special "configuration" block inside Pydantic. It tells the model how to behave. 
    # In 2026 (Pydantic v2), you might also see this written as model_config
    # They act as a translator. By setting orm_mode = True (or from_attributes = True), you are telling Pydantic: "Don't worry if the data isn't a dictionary. If you see an object, just use the dot (.) notation to pull the values out."
    class config:
        # allows FastAPI to return SQLAlcgemy objects directly
        # without this FastAPI would crash trying to serialize ORM models
        orm_mode = True




